fos_user:
    db_driver: orm
    firewall_name: main
    user_class: FOS\UserBundle\Entity\User
    from_email:
        address: "my@mail.com"
        sender_name: "Name Surname"
    group:
        group_class:   FOS\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
framework:
    templating:
        engines: ['twig', 'php']