sonata_media:
    class:
        media:              App\Entity\SonataMediaMedia
        gallery:            App\Entity\SonataMediaGallery
        gallery_has_media:  App\Entity\SonataMediaGalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 200 , quality: 80}
                big:   { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
        product:
            providers:
                - sonata.media.provider.image
            formats:
                small:  { width: 200 , quality: 80 }
                big:   { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false
