sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false

    assets:
        extra_javascripts: ['bundles/pixsortablebehavior/js/jquery-ui.min.js', 'bundles/pixsortablebehavior/js/init.js']

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
