homepage:
   path: /
   controller: App\Controller\DefaultController::homepage
product:
   path: /product/{id}
   controller: App\Controller\DefaultController::product
category:
   path: /category/{id}
   controller: App\Controller\DefaultController::category
   defaults:
      id: 0

sonata_user_admin_security:
   resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
   prefix: /admin

sonata_user_admin_resetting:
   resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
   prefix: /admin/resetting