homepage:
   path: /
   controller: App\Controller\DefaultController::homepage
product:
   path: /product/{id}
   controller: App\Controller\DefaultController::product
category:
   path: /category/{id}
   controller: App\Controller\DefaultController::category